### ISSUE TITLE
关于yololoss的疑问

### ISSUE THREAD

**Issue by yuanliangxie** [Peterisfar/YOLOV3#10]
您的代码非常简练有力！赞！
但是我对于yololoss有一些疑问：
您的策略貌似跟yolov3论文的策略不一样啊
gtbox与每层feature_map中的pred_anchor进行IOU计算，如果IOU>0.3即进行assign为positive操作。若gt_box与所有feature_map中的pred_anchor的IOU都小于0.3时，取所有feature_map中最大的anchor进行assign
而我理解的yolov3策略是
gtbox与所有feature_map中的pred_anchor进行IOU计算，挑选IOU最大的哪一个进行assign.
请问这样做有什么好处吗？希望能与您交流一二

**Comment by Peterisfar** [comment]
感谢您对我工程的关注，这里GT分配策略跟原先不同，借鉴retinaNet、fasterRcnn的套路改的，好处的话主要是每个GT可能由不同层的anchor负责或者同层多个anchor负责；每个GT至少有一个anchor负责。相比原先的策略多了同层多个anchor预测，并且由于使用了IoU阈值则减少了那些IoU非常低的anchor数量，即由3变成1.
