### ISSUE TITLE
augment

### ISSUE THREAD

**Issue by gjfzjj1995** [Peterisfar/YOLOV3#12]
你好，首先感谢您分享的代码，我想问一下在数据增强那里有个mixup函数，为什么要采用beta分布来设置进行图像数据的混合，而且class_id后面一个参数为什么是0-1？？

**Comment by Peterisfar** [comment]
选用beta参考的亚马逊的一篇paper,class_id指的是哪里的，不太明白你的问题

**Comment by gjfzjj1995** [comment]
谢谢回答，能否将beta相关论文的链接发一下，谢谢了

**Comment by Peterisfar** [comment]
> 谢谢回答，能否将beta相关论文的链接发一下，谢谢了

Bag of Freebies for Training Object Detection Neural Networks

**Comment by gjfzjj1995** [comment]
非常感谢您的帮助
