### ISSUE TITLE
Dear author, thank you for your code. How many epoches have you trained for pascal voc to get map 85%?  Is the batches set by 8? 

### ISSUE THREAD

**Issue by jumoran** [Peterisfar/YOLOV3#13]

**Comment by Peterisfar** [comment]
In the master branch, 50  epochs, batchsize is 8. And in the model_compression branch, 120 epochs, batchsize is 8.

**Comment by jumoran** [comment]
Thank you for your help. I have trained for 50 epoches in the master branch. The best map is only 80.6%. what is your final loss ?

**Comment by Peterisfar** [comment]
> Thank you for your help. I have trained for 50 epoches in the master branch.

first, are you sure the branch is "master" ? second, final loss you can see the nohup.log. third, 85% is based on the multi-scale test and flip test. 

by the way, you can check your commit is the new?

**Comment by jumoran** [comment]
thank you for your help. I have found the error. because of the different version of python
