### ISSUE TITLE
每个epoch训练完之后validate的速度特别慢？

### ISSUE THREAD

**Issue by Shank2358** [Peterisfar/YOLOV3#19]
感谢您的代码，请问每个epoch训练完之后validate的batchsize可以修改吗（现在我运行的时候是单张图片计算的，2007test好多图片，每个epoch验证都要很久），是否是我的参数没设置对，我应该如何修改，因为每跑完一个epoch就要花很长时间在validation上，速度特别慢。请问我该如何解决这个问题。谢谢。

**Comment by Peterisfar** [comment]
目前只支持batchsize=1进行validate，如果要多batchsize需要修改eval中的函数。test2007我的验证时间是5、6分钟左右（20个epoch以后开始验证）

**Comment by Shank2358** [comment]
> 目前只支持batchsize=1进行validate，如果要多batchsize需要修改eval中的函数。test2007我的验证时间是5、6分钟左右（20个epoch以后开始验证）

谢谢你的回复，我暂时修改成了每5个epoch验证一次（我的显卡不是很好，时间比较久），我这就详细学习一下eval的函数修改看看，谢谢。

**Comment by DanevenChin** [comment]
你好，我也遇到了同样的问题，我在特斯拉v100上算一次mAP需要1h时间，有什么好的解决办法吗？

**Comment by Peterisfar** [comment]
> 你好，我也遇到了同样的问题，我在特斯拉v100上算一次mAP需要1h时间，有什么好的解决办法吗？

什么时候开始计算mAP的，开了多尺度测试了吗

**Comment by DanevenChin** [comment]
> 
> 
> > 你好，我也遇到了同样的问题，我在特斯拉v100上算一次mAP需要1h时间，有什么好的解决办法吗？
> 
> 什么时候开始计算mAP的，开了多尺度测试了吗

我是在模型训练收敛后测试性能，发现速度很慢，multi_scale和flip都没有开

**Comment by DanevenChin** [comment]
测试了一下各个环节的耗时，发现源码中的NMS特别耗时，模型推断时间在0.02~0.1s之间，而做NMS时耗时1.2s以上，换成其他版本的NMS，这部分耗时降到0.01s以下。

**Comment by Peterisfar** [comment]
> 测试了一下各个环节的耗时，发现源码中的NMS特别耗时，模型推断时间在0.02~0.1s之间，而做NMS时耗时1.2s以上，换成其他版本的NMS，这部分耗时降到0.01s以下。

第几个epoch开始测mAP的，一直在收敛啊

**Comment by Shank2358** [comment]
> 测试了一下各个环节的耗时，发现源码中的NMS特别耗时，模型推断时间在0.02~0.1s之间，而做NMS时耗时1.2s以上，换成其他版本的NMS，这部分耗时降到0.01s以下。

请问用的是哪个版本的NMS，可以分享一下吗。我看了一下NMS的函数，代码里好像用的numpy，是不是改成torch会快一点。

**Comment by Peterisfar** [comment]
使用nms需要注意，要训练到一定epochs后才进行评价，不然前期置信度低的框很多导致循环周期过长。另外，如果有好的nms实现方式，希望大家可以在这里分享提供相互学习的机会。thanks

**Comment by crownz-sec** [comment]
> 测试了一下各个环节的耗时，发现源码中的NMS特别耗时，模型推断时间在0.02~0.1s之间，而做NMS时耗时1.2s以上，换成其他版本的NMS，这部分耗时降到0.01s以下。

**Comment by crownz-sec** [comment]
> 测试了一下各个环节的耗时，发现源码中的NMS特别耗时，模型推断时间在0.02~0.1s之间，而做NMS时耗时1.2s以上，换成其他版本的NMS，这部分耗时降到0.01s以下。

你好，请问这个nms是哪个版本的呢，是否可以分享学习下呢？

**Comment by starzero-hhh** [comment]
> > 目前只支持batchsize=1进行validate，如果要多batchsize需要修改eval中的函数。test2007我的验证时间是5、6分钟左右（20个epoch以后开始验证）
> 
> 谢谢你的回复，我暂时修改成了每5个epoch验证一次（我的显卡不是很好，时间比较久），我这就详细学习一下eval的函数修改看看，谢谢。

您好，请问是在哪里设置的每5个epoch验证一次，我也是每次训练完了验证的速度特别慢
