### ISSUE TITLE
Dear author, why do you choose alpha =1.0 in the focal loss?

### ISSUE THREAD

**Issue by jumoran** [Peterisfar/YOLOV3#21]

**Comment by Lornatang** [comment]
@jumoran 
The correct setting is `gamma=1.5, alpha=0.25`

**Comment by Peterisfar** [comment]
It is not absolute, you can use the alpha coefficient to balance the positive and negative sample proportions or not. I didn't use it here, only gamma = 2.0. you can try to add alpha just modify the loss.py.
