### ISSUE TITLE
About utils/datasets.py

### ISSUE THREAD

**Issue by GesilaA** [Peterisfar/YOLOV3#30]
line111:       for i in range(3):
 line112:           label[i][..., 5] = 1.0

Why set the conf of map pixels to 1.0? It means all pixels contains obj?

**Comment by Peterisfar** [comment]
> line111: for i in range(3):
> line112: label[i][..., 5] = 1.0
> 
> Why set the conf of map pixels to 1.0? It means all pixels contains obj?

 label[i][..., 5] is mixup weight,default is 1.0
