### ISSUE TITLE
index 56 is out of bound for axis 1 with size 56?

### ISSUE THREAD

**Issue by ghost** [Peterisfar/YOLOV3#32]
when I run this code to trian on VOC, I met the following bug:
"index 56 is out of bound for axis 1 with size 56", 

It caused by the following sentences in "utils/dataset.py" :
label[i][yind, xind, iou_mask, 0:4] = bbox_xywh
label[i][yind, xind, iou_mask, 4:5] = 1.0
Iabel[i][yind, xind, iou_mask, 5:6] = bbox_mix
label[i][yind, xind, iou_mask, 6:] = one_hot_smooth
How can I solve it? Thanks for your help.

**Comment by ToolmanInside** [comment]
@huaiyuyaya Hi, have you solved it? I also met this error when I trained on my customized VOC dataset
