### ISSUE TITLE
【Question】Batch size?

### ISSUE THREAD

**Issue by neesetifa** [Peterisfar/YOLOV3#34]
您好, 我看到config文件里batch size设置为8，仔细阅读代码后也没有发现其他地方会更改batch size。 我看到你的显卡是2080ti，挺好的显卡了，请问batch size设置这么小是有什么特殊原因吗？ 
谢谢

**Comment by Peterisfar** [comment]
> 您好, 我看到config文件里batch size设置为8，仔细阅读代码后也没有发现其他地方会更改batch size。 我看到你的显卡是2080ti，挺好的显卡了，请问batch size设置这么小是有什么特殊原因吗？
> 谢谢

显卡是11g的，因为里面涉及到多尺度训练，batch size设置为8差不多合适

**Comment by neesetifa** [comment]
@Peterisfar 谢谢懂了～那我根据自己显卡大小调整这个值
