### ISSUE TITLE
Change backbone

### ISSUE THREAD

**Issue by andyJJz** [Peterisfar/YOLOV3#35]
could I change backbone to resnet50?

**Comment by Peterisfar** [comment]
> could I change backbone to resnet50?

yes

**Comment by andyJJz** [comment]
Could I use this repo to do some extension research about object detection? maybe publish paper later.发自我的华为手机-------- 原始邮件 --------发件人： leon <notifications@github.com>日期： 2020年11月11日周三 下午3:07收件人： Peterisfar/YOLOV3 <YOLOV3@noreply.github.com>抄送： andyJJz <18379273937@163.com>, Author <author@noreply.github.com>主    题： Re: [Peterisfar/YOLOV3] Change backbone (#35)

could I change backbone to resnet50?

yes

**Comment by Peterisfar** [comment]
> Could I use this repo to do some extension research about object detection? maybe publish paper later.发自我的华为手机-------- 原始邮件 --------发件人： leon <notifications@github.com>日期： 2020年11月11日周三 下午3:07收件人： Peterisfar/YOLOV3 <YOLOV3@noreply.github.com>抄送： andyJJz <18379273937@163.com>, Author <author@noreply.github.com>主 题： Re: [Peterisfar/YOLOV3] Change backbone (#35) could I change backbone to resnet50? yes —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

you can

**Comment by andyJJz** [comment]
Thank you so much.发自我的华为手机-------- 原始邮件 --------发件人： leon <notifications@github.com>日期： 2020年11月12日周四 下午3:46收件人： Peterisfar/YOLOV3 <YOLOV3@noreply.github.com>抄送： andyJJz <18379273937@163.com>, Author <author@noreply.github.com>主    题： Re: [Peterisfar/YOLOV3] Change backbone (#35)



Could I use this repo to do some extension research about object detection? maybe publish paper later.发自我的华为手机-------- 原始邮件 --------发件人： leon notifications@github.com日期： 2020年11月11日周三 下午3:07收件人： Peterisfar/YOLOV3 YOLOV3@noreply.github.com抄送： andyJJz 18379273937@163.com, Author author@noreply.github.com主 题： Re: [Peterisfar/YOLOV3] Change backbone (#35) could I change backbone to resnet50? yes —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.



you can
