### ISSUE TITLE
LOSS

### ISSUE THREAD

**Issue by Gaondong** [Peterisfar/YOLOV3#4]
Sorry to bother you, I read your comment in ultralytics / yolov3.  Did you changed his loss function to the original YOLOV3 paper version?

**Comment by Peterisfar** [comment]
Yes, i change the loss,  because i think his loss function is different from original loss in the Darknet.

**Comment by Gaondong** [comment]
> Yes, i change the loss, because i think his loss function is different from original loss in the Darknet.

OK , Thank you very much.

**Comment by Peterisfar** [comment]
> > Yes, i change the loss, because i think his loss function is different from original loss in the Darknet.
> 
> OK , Thank you very much.
