### ISSUE TITLE
What's the difference between darknet53-448.weights and darknet53.conv.74?

### ISSUE THREAD

**Issue by crownz-sec** [Peterisfar/YOLOV3#40]
Both of them can be download from YOLOv3 author's website, but now there is only darknet53.conv.74 showed on the YOLOv3's page.SO I am hesitating which one to use to pre-train the network. 
Can anyone tell me the difference between them?

**Comment by Peterisfar** [comment]
> Both of them can be download from YOLOv3 author's website, but now there is only darknet53.conv.74 showed on the YOLOv3's page.SO I am hesitating which one to use to pre-train the network.
> Can anyone tell me the difference between them?

darknet53-448's weights are complete, but darknet53.conv.74 only contain previous 74 layers.

**Comment by crownz-sec** [comment]
> > Both of them can be download from YOLOv3 author's website, but now there is only darknet53.conv.74 showed on the YOLOv3's page.SO I am hesitating which one to use to pre-train the network.
> > Can anyone tell me the difference between them?
> 
> darknet53-448's weights are complete, but darknet53.conv.74 only contain previous 74 layers.

okay, thanks
