### ISSUE TITLE
Training on custom dataset guide and Image, video detection demo

### ISSUE THREAD

**Issue by smalldroid** [Peterisfar/YOLOV3#6]
Would you like to add training on custom dataset guide and Image, video detection demo. Thank you!

**Comment by Peterisfar** [comment]
To train the custom dataset, you can convert it to voc format or directly  make a code to get the "custom_train.txt" and "custom _test.txt"  like "train_annotation.txt" and "test_annotation.txt". And you also should update the eval/evaluator.py......

Now i have something to do, maybe next month i will add these. Sorry.
