### ISSUE TITLE
关于训练

### ISSUE THREAD

**Issue by yehaizi1995** [Peterisfar/YOLOV3#7]
你好　我按照你写的步骤去训练　但是这一行代码我没看懂是什么意思，是写错了还是？希望有空能解答一下。代码如下：
`CUDA_VISIBLE_DEVICES=0 nohup python3 -u train.py --weight_path $WEIGHT_PATH --gpu_id 0 > nohup.log 2>&1 &
`

**Comment by Peterisfar** [comment]
just baidu or google
